### ISSUE TITLE
Header files

### ISSUE THREAD

**Issue by uday-3773** [Sivapriyapj/SDLC_22_Technovators#6]
main driver code should be implemented separately, remove it from header files.

**Comment by thomasathul** [comment]
Hi team, Function definitions should be part of c file. Header files should include only prototypes and function definitions. The same function definition will be applied to every source files and there's a case of redundancy.

**Comment by Sivapriyapj** [comment]
Electronic,medical,banking calculator implemented as .c files instead of header. Arithematic and Scientific are to be changed
